apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: project-complex #if you change this, you need to change the name the folder project-complex where charts are in.
version: 0.1.0
