apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment

spec:
  replicas: 1 #number of different pods that we are going to setup
  selector: #define a selector that this specific deployment(client)is going to use to find these set of pods that it's supposed to control.
    matchLabels:
      component: web
  template: #putting together pod template for the pods that are going to be created
    metadata:
      labels:
        component: web
    spec:
      containers: #provide containers that this pods that its supposed to run
        - name: client
          image: rhedgomez/multi-client:testing-image #nginx image
          ports:
            - containerPort: 3000 #port that is mapped-up to the mulit-client image.
            